apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-dep
  labels:
    app: fitness-app
spec:
  replicas: {{.values.replicas}}
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: {{.values.labels.app}}
    spec:
      containers:
      - name: {{.values.container.name}}
        image: {{.values.container.image}}
        ports:
          - containerPort: {{.values.container.port}}
        envFrom:
          - configMapRef:
              name: {{.values.configmap.name}}
          - secretRef:
              name: {{.values.secret.name}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.values.service.name}}
spec:
  selector:
    app: fitness-app
  ports:
    - protocol: TCP
      port: {{.values.service.port}}
      targetPort: {{.values.service.targetPort}}
  type: {{.values.service.type}}